//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metalkit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int Id { get; set; }
        public Nullable<int> Rut { get; set; }
        public string Dv { get; set; }
        public string RazonSocial { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> IdComuna { get; set; }
        public string Giro { get; set; }
        public string NombreContacto { get; set; }
        public string ApellidoContacto { get; set; }
        public string CorreoContacto { get; set; }
        public string TelefonoContacto { get; set; }
    }
}
