//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metalkit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cotizacion
    {
        public int Id { get; set; }
        public Nullable<int> IdProductoParametro { get; set; }
        public Nullable<int> IdEntrega { get; set; }
        public Nullable<int> IdTipoProyecto { get; set; }
        public Nullable<int> IdCliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Entrega Entrega { get; set; }
        public virtual Producto_Parametro Producto_Parametro { get; set; }
        public virtual TipoProyecto TipoProyecto { get; set; }
    }
}
