//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metalkit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoOT_VersionOT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EstadoOT_VersionOT()
        {
            this.VersionOT = new HashSet<VersionOT>();
        }
    
        public int Id { get; set; }
        public int IdEstadoOT { get; set; }
        public int IdVersionOT { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public int IdUsuario { get; set; }
    
        public virtual EstadoOT EstadoOT { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VersionOT> VersionOT { get; set; }
    }
}
